core/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    # path('', views.LandingPageView.as_view(), name='landing_page'),
    path('', views.LoginView.as_view(), name='login'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('backend/', include('backend.urls')),
    path('vote/', include('voting.urls')),
]

# Let django serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/voting/urls.py
from django.urls import path
from . import views as views


app_name = 'voting'

# generals
urlpatterns = [
    path('instructions/', views.InstructionsView.as_view(), name='instructions'),
    path('castvote/', views.CastVoteView.as_view(), name='cast_vote'),  # noqa
    path('votecompleted/', views.VoteCompletedView.as_view(), name='vote_completed'),  # noqa
    path('alreadyvoted/', views.AlreadyVotedView.as_view(), name='already_voted'),  # noqa
]

core/voting/models.py
from django.db import models

# Create your models here.

core/voting/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.utils.decorators import method_decorator
from django.db import models
from django.contrib import messages

from backend.models import Candidate, Position
from core.utils.decorators import MustLogin
from core.utils.constants import PositionName, Sex
from core.utils.utils import get_next_position


class InstructionsView(View):
    '''Entry point of election'''
    template = 'voting/instructions.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        next_position_indx = get_next_position(request)
        if next_position_indx == -999:
            return redirect('voting:already_voted')
        return render(request, self.template, {})

class CastVoteView(View):
    '''General view for casting votes'''
    template = 'voting/vote.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        next_position_indx, is_house_prefect = get_next_position(request)
        candidates = Candidate.objects.none() 
        if next_position_indx == -999:
            return redirect('voting:already_voted')
        
        if is_house_prefect: # House Prefect position
            # filter candidates based on voter's house
            positions = Position.objects.annotate(num_candidates=models.Count('candidate')).filter(num_candidates__gt=0).order_by("precedence")
            next_position_indx -= 1  # adjust for zero-based index
            position = positions[next_position_indx]
            user_house = request.user.house
            candidates = Candidate.objects.filter(position=position, house__icontains=user_house).order_by('ballot_number')
        else:
            next_position_indx -= 1  # adjust for zero-based index
            positions = Position.objects.annotate(num_candidates=models.Count('candidate')).filter(num_candidates__gt=0).order_by("precedence")
            position = positions[next_position_indx]
            candidates = Candidate.objects.filter(position=position).order_by('ballot_number')
        # flag for yes or no vote
        if candidates.count() == 1:
            acclamation = True
        else:
            acclamation = False
        context = {
            'position': position.name,
            'candidates': candidates,
            'acclamation': acclamation,
        }
        return render(request, self.template, context)
    
    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        next_position_indx, is_house_prefect = get_next_position(request)
        if next_position_indx == -999:
            request.user.already_voted = True
            request.user.save()
            return redirect('voting:already_voted')
        next_position_indx -= 1  # adjust for zero-based index

        # check for acclamation vote | Yes, No
        acclamation = True if request.POST.get('acclamation') is not None else False  # noqa
        candidate_id = request.POST.get('candidate_id')
        no_vote = request.POST.get('no_vote') or None


        if is_house_prefect: # House Prefect position
            # filter candidates based on voter's house
            positions = Position.objects.annotate(num_candidates=models.Count('candidate')).filter(num_candidates__gt=0).order_by("precedence")
            position = positions[next_position_indx]
            user_house = request.user.house
            # candidate = Candidate.objects.filter(position=position, house__icontains=user_house).order_by('ballot_number')
            candidate = Candidate.objects.filter(position=position, id=candidate_id, house__icontains=user_house).first()
        else:
            positions = Position.objects.annotate(num_candidates=models.Count('candidate')).filter(num_candidates__gt=0).order_by("precedence")
            position = positions[next_position_indx]
            candidate = Candidate.objects.filter(position=position, id=candidate_id).first()
        
        if acclamation and no_vote == "NO":
            if candidate:
                candidate.no_votes_count += 1
                candidate.save()
                request.user.total_votes_cast += 1
                request.user.save()
                return redirect('voting:cast_vote')
        # not an acclamation vote
        if not candidate:
            print(f"Invalid candidate selected: {candidate_id} for position {position.name}")  # noqa
            messages.error(request, 'Invalid Candidate Selected')
            return redirect('voting:cast_vote')
        candidate.vote_count += 1
        candidate.save()
        request.user.total_votes_cast += 1
        request.user.save()
        positions_count = positions = Position.objects.annotate(num_candidates=models.Count('candidate')).filter(num_candidates__gt=0).count()
        if request.user.total_votes_cast >= positions_count:
            request.user.already_voted = True
            request.user.save()
            return redirect('voting:vote_completed')
        messages.success(request, 'Vote Successful, Proceed to next portfolio.')  # noqa
        return redirect('voting:cast_vote')

class VoteCompletedView(View):
    '''View to show the vote has been completed'''
    template = 'voting/vote_completed.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        return render(request, self.template, {})


class AlreadyVotedView(View):
    '''View to show the user has already voted'''
    template = 'voting/already_voted.html'

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        return render(request, self.template, {})

core/voting/templates/voting/already_voted.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <title>Tashtech SRC | Already Voted </title>
</head>

<body>
    <div class="container text-center">
        <div class="container mt-5">
            <img src="{% static 'images/illustrations/cant-vote.png' %}" alt=""
                style="height: 200px; width:auto; border: 2px dashed red;">
        </div>
        <div class="container">
            <h4 style="font-family: 'Lobster', cursive; font-size: 80px; font-weight: 500; color: red; ">
                Access Denied!</h4>
            <p>You have already voted.</p>
        </div>
        <div class="container">
            <a href="{% url 'accounts:login' %}" class="btn btn-sm btn-primary">Finish</a>
        </div>
    </div>
</body>

</html>

core/voting/templates/voting/instructions.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Tashtech SRC | Start Vote</title>
</head>

<body>
    <div class="container" style="background-color: rgb(236, 236, 232);">
        <div class="row">
            <div class="col-md-12 mt-5">
                <!-- CANDIDATE -->
                <div class="card mb-3">
                    <div class="card-header text-center">
                        <h3>INSTRUCTIONS</h3>
                    </div>
                    <!--  -->
                    <div class="card-body mb-5">
                        <div class="row d-flex justify-content-center">
                            <div class="col-8 text-center mb-3">
                                <img src="{% static 'images/illustrations/how_to_vote.png' %}" alt="instructions"
                                    style="height: 200px; width:auto; border: 2px solid blueviolet; margin: 15px auto;">
                            </div>
                            <div class="col-8">
                                <b>Read these carefully</b>
                                <p>Ensure you are voting for the right candidate because once you vote for a portfolio,
                                    you can not undo it.</p>
                                <p>When you are sure you want to vote for a candidate, click on the <b>'Vote'</b> button
                                    underneath their details.</p>
                                <p>Once you vote for a portfolio, the system will automatically redirect you to the next
                                    portfolio.</p>
                                <p>Once you reach the <b>'Voting Completed'</b> page, click on the <b>'Finish'</b>
                                    button
                                    and leave
                                    the
                                    pollin station</p>
                            </div>
                            <div class="col-8">
                                <a href="{% url 'voting:cast_vote' %}" class="btn btn-sm btn-primary">Continue to Voting
                                    Page</a>
                            </div>
                        </div>

                    </div>
                    <!--  -->
                </div>
                <!-- /CANDIDATE -->
            </div>
        </div>
    </div>
</body>

</html>

core/voting/templates/voting/vote.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Tashtech SRC | Vote - {{position}} </title>
</head>

<body>
    <div class="container" style="background-color: rgb(243, 241, 241);">
        <div class="row">
            <div class="col-md-12 mt-5">
                <!--  -->
                <div class="card mb-2">
                    <div class="card-header">
                        <h3 class="text-center">{{position|upper}}</h3>
                    </div>
                </div>

                {% for candidate in candidates %}
                <!-- CANDIDATE -->
                <div class="card mb-3">
                    <div class="card-header">
                        <h3>{{candidate.name|upper}}</h3>
                    </div>
                    <!--  -->
                    <div class="card-body">
                        <div class="row">
                            <div class="col-4">
                                <img src="{% if candidate.picture %} {{candidate.picture.url}} {% else %} {% static 'images/illustrations/user.png' %} {% endif %} "
                                    alt="candidate" style="height: 200px; width:auto;">
                            </div>
                            <div class="col-4">
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="candidate_id" value="{{candidate.id}}">
                                    <!-- <input type="hidden" name="no_vote" value="NO"> -->
                                    <!-- <input type="hidden" name="acclamation" value="1"> -->
                                    <div class="form-group mb-2">
                                        <label for=""> <b>Candidate Name</b></label>
                                        <p>{{candidate.name|upper}}</p>
                                    </div>
                                    <div class="form-group mb-2">
                                        <label for=""><b>Nickname</b></label>
                                        <p>{{candidate.nickname|upper}}</p>
                                    </div>
                                    <div class="form-group mb-2">
                                        <label for=""><b>Position</b></label>
                                        <p>{{candidate.position.name|upper}}</p>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-primary">{% if acclamation %}Yes{% else %}
                                            Vote{% endif %}</button>
                                    </div>
                                </form>
                                {% if acclamation %}
                                <form action="" method="POST" class="mt-1">
                                    {% csrf_token %}
                                    <input type="hidden" name="candidate_id" value="{{candidate.id}}">
                                    <input type="hidden" name="no_vote" value="NO">
                                    <input type="hidden" name="acclamation" value="1">
                                    <div class="form-group">
                                        <button class="btn btn-sm btn-danger">No Vote</button>
                                    </div>
                                </form>
                                {% endif %}
                            </div>
                            <div class="col-4">
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    <div class="form-group mb-2">
                                        <label for=""> <b>Candidate Sex</b></label>
                                        <p>{{candidate.sex|upper}}</p>
                                    </div>
                                    <div class="form-group mb-2">
                                        <label for=""><b>House</b></label>
                                        <p>{{candidate.house|upper}}</p>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!--  -->
                </div>
                <!-- /CANDIDATE -->
                {% endfor %}
            </div>
        </div>
    </div>
</body>

</html>

core/voting/templates/voting/vote_completed.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <title>Tashtech SRC | Vote Completed </title>
</head>

<body>
    <div class="container text-center">
        <div class="container mt-5">
            <img src="{% static 'images/illustrations/vote.png' %}" alt=""
                style="height: 200px; width:auto; border: 2px dashed blueviolet;">
        </div>
        <div class="container">
            <h4 style="font-family: 'Lobster', cursive; font-size: 80px; font-weight: 500; color: blueviolet; ">
                CONGRATIONS!</h4>
            <p>You have successfully voted. Click on the button bellow and leave the pollin station.</p>
        </div>
        <div class="container">
            <a href="{% url 'accounts:login' %}" class="btn btn-sm btn-primary">Finish</a>
        </div>
    </div>
</body>

</html>