core/backend/urls.py
from unicodedata import name
from django.urls import path
from . import views


app_name = 'backend'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.NewDashboardView.as_view(), name='index'),
]

# new dashboard
urlpatterns += [
    path('new-dashboard/', views.NewDashboardView.as_view(), name="new_dashboard"),
]

# Candidates
urlpatterns += [
    path('candidates/', views.CandidatesListView.as_view(), name='candidates'),
    path('create-update-candiddate/', views.CreateUpdateCandidateView.as_view(), name='create_update_candidate'),  # noqa
    path('delete-candidate/', views.DeleteCandidateView.as_view(), name='delete_candidate')  # noqa
]

# Positions
urlpatterns += [
    path('positions/', views.PositionsView.as_view(), name='positions'),
    path('create-update_position/', views.CreateUpdatePositionView.as_view(), name='create_update_position'),  # noqa
    path('upload-position-csv/', views.UploadPositionsFromCSV.as_view(), name='upload_position_csv'),  # noqa
    path('delete-position/', views.DeletePositionView.as_view(), name='delete_position'),  # noqa
]

# Elections
urlpatterns += [
    path('elections/', views.ElectionsView.as_view(), name='elections'),
    path('create-update_election/', views.CreateUpdateElectionView.as_view(), name='create_update_election'),  # noqa
    path('delete-election/', views.DeleteElectionView.as_view(), name='delete_election'),  # noqa
]

# Voters
urlpatterns += [
    path('voters/', views.VotersView.as_view(), name='voters'),
    path('create-update_voter/', views.CreateUpdateVoterView.as_view(), name='create_update_voter'),  # noqa
    path('delete-voter/', views.DeleteVoterView.as_view(), name='delete_voter'),  # noqa
    path('upload-register/', views.UploadVotersFromCSV.as_view(), name='upload_register'),  # noqa
]


# Verification
urlpatterns += [
    path('verification/', views.VerificationView.as_view(), name='verification'),
]

# Results
urlpatterns += [
    path('download-results-csv/', views.DownloadCandidateResultsAsCSVView.as_view(), name='download_results_csv'),  # noqa
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('backend/', include('backend.urls')),
    path('vote/', include('voting.urls')),
]

# Let django serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/backend/forms.py
from django import forms

from .models import Candidate, Election, Position


class CandidateForm(forms.ModelForm):
    '''Facilitates creation and updation of candidates'''
    class Meta:
        model = Candidate
        exclude = ['vote_count', 'position', 'created_at', 'no_votes_count']


class PositionForm(forms.ModelForm):
    '''Facilitates creation and updation of positions'''
    class Meta:
        model = Position
        exclude = ['created_at']


class ElectionForm(forms.ModelForm):
    '''Facilitates creation and updation of elections'''
    class Meta:
        model = Election
        exclude = ['created_at', 'is_active']

core/backend/views/candidates.py
import csv
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.utils.html import strip_tags
from django.views.generic import View
from django.http.response import HttpResponse
from backend.forms import CandidateForm

from backend.models import Candidate, Position
from core.utils.decorators import AdminOnly


class CandidatesListView(View):
    template = 'backend/lists/candidates.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        context = {'candidates': Candidate.objects.all().order_by('position__name', 'ballot_number')}  # noqa
        return render(request, self.template, context)


class CreateUpdateCandidateView(View):
    '''Class for creating and updating candidates'''
    template = 'backend/create_update_candidate.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        candidate_id = request.GET.get('candidate_id')
        candidate = Candidate.objects.filter(id=candidate_id).first()
        positions = Position.objects.all()
        context = {'positions': positions, 'candidate': candidate}
        return render(request, self.template, context)

    @method_decorator(AdminOnly)
    def post(self, request, *args, **kwargs):
        position_id = request.POST.get('position')
        candidate_id = request.POST.get('candidate_id')
        position = Position.objects.filter(id=position_id).first()

        if candidate_id:
            # candidate exists
            candidate = Candidate.objects.filter(id=candidate_id).first()
            form = CandidateForm(request.POST, request.FILES, instance=candidate)  # noqa
            if form.is_valid():
                candidate = form.save(commit=False)
                candidate.position = position
                candidate.save()
                messages.success(request, 'Candidate Details Updated Successfully.')  # noqa
                return redirect('backend:candidates')
            else:
                for field, error in form.errors.items():
                    message = f"{field.title()}: {strip_tags(error)}"
                    break
                messages.warning(request, message)
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
        else:
            # it's a new candidate
            form = CandidateForm(request.POST, request.FILES)
            if form.is_valid():
                candidate = form.save(commit=False)
                candidate.position = position
                candidate.save()
                messages.success(request, 'New Candidate Created Successfully.')  # noqa
                return redirect('backend:candidates')
            else:
                for field, error in form.errors.items():
                    message = f"{field.title()}: {strip_tags(error)}"
                    break
                messages.warning(request, message)
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


class DeleteCandidateView(View):
    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        return redirect('backend:candidates')

    @method_decorator(AdminOnly)
    def post(self, request, *args, **kwargs):
        candidate_id = request.POST.get('candidate_id')
        candidate = Candidate.objects.filter(id=candidate_id)
        candidate.delete()
        messages.success(request, 'Candidate Deleted Successfully!')
        return redirect('backend:candidates')


class DownloadCandidateResultsAsCSVView(View):
    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="election_results.csv"'  # noqa

        writer = csv.writer(response)
        writer.writerow(
            ['BALLOT NO.', 'POSITION', 'CANDIDATE', 'VOTES COUNT', 'NO VOTES', 'YES VOTE COUNT %', 'NO VOTES %'])  # noqa

        candidates = Candidate.objects.all().order_by('position__precedence', 'ballot_number')  # noqa
        for candidate in candidates:
            writer.writerow(
                [
                    candidate.ballot_number,
                    candidate.position.name,
                    candidate.name,
                    candidate.vote_count,
                    candidate.no_votes_count,
                    candidate.get_vote_percentage(),
                    candidate.get_no_vote_percentage(),
                ]
            )
        return response

core/backend/views/dashboard.py
from django.shortcuts import render
from django.views import View

from backend.models import Candidate, Election, Position
from django.utils.decorators import method_decorator
from core.utils.constants import House, PositionName
from core.utils.decorators import AdminOnly


class IndexView(View):
    template = 'backend/index.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        current_election = Election.objects.filter(is_active=True).order_by('created_at').first()  # noqa
        positions_set_1 = Position.objects.all().order_by('-id')[:10]
        positions_set_2 = Position.objects.all().order_by('-id')[10:]

        sps = Candidate.objects.filter(position__name=PositionName.SP.value).order_by('ballot_number')  # noqa
        gps = Candidate.objects.filter(position__name=PositionName.GP.value).order_by('ballot_number')  # noqa

        cob = Candidate.objects.filter(position__name=PositionName.COB.value).order_by('ballot_number')  # noqa
        cog = Candidate.objects.filter(position__name=PositionName.COG.value).order_by('ballot_number')  # noqa

        sgpb = Candidate.objects.filter(position__name=PositionName.SGPB.value).order_by('ballot_number')  # noqa
        sgpg = Candidate.objects.filter(position__name=PositionName.SGPG.value).order_by('ballot_number')  # noqa

        dhpb = Candidate.objects.filter(position__name=PositionName.DHPB.value).order_by('ballot_number')  # noqa
        dhpg = Candidate.objects.filter(position__name=PositionName.DHPG.value).order_by('ballot_number')  # noqa

        ecpb = Candidate.objects.filter(position__name=PositionName.ECPB.value).order_by('ballot_number')  # noqa
        ecpg = Candidate.objects.filter(position__name=PositionName.ECPG.value).order_by('ballot_number')  # noqa

        plpb = Candidate.objects.filter(position__name=PositionName.PLPB.value).order_by('ballot_number').first()  # noqa
        plpg = Candidate.objects.filter(position__name=PositionName.PLPG.value).order_by('ballot_number').first()  # noqa

        csb = Candidate.objects.filter(position__name=PositionName.CSB.value).order_by('ballot_number').first()  # noqa
        csg = Candidate.objects.filter(position__name=PositionName.CSG.value).order_by('ballot_number').first()  # noqa

        # ppb = Candidate.objects.filter(position__name=PositionName.PPB.value).order_by('ballot_number')  # noqa
        # ppg = Candidate.objects.filter(position__name=PositionName.PPG.value).order_by('ballot_number')  # noqa

        hspb = Candidate.objects.filter(position__name=PositionName.HSPB.value).order_by('ballot_number')  # noqa
        hspg = Candidate.objects.filter(position__name=PositionName.HSPG.value).order_by('ballot_number').first()  # noqa

        hpba = Candidate.objects.filter(position__name=PositionName.HPB.value, house=House.ASANTE.value).order_by('ballot_number').first()  # noqa
        hpga = Candidate.objects.filter(position__name=PositionName.HPG.value, house=House.ASANTE.value).order_by('ballot_number').first()  # noqa

        hpbb = Candidate.objects.filter(position__name=PositionName.HPB.value, house=House.BOTWE.value).order_by('ballot_number').first()  # noqa
        hpgb = Candidate.objects.filter(position__name=PositionName.HPG.value, house=House.BOTWE.value).order_by('ballot_number').first()  # noqa

        hpbka = Candidate.objects.filter(position__name=PositionName.HPB.value, house=House.KALEDZI.value).order_by('ballot_number').first()  # noqa
        hpgka = Candidate.objects.filter(position__name=PositionName.HPG.value, house=House.KALEDZI.value).order_by('ballot_number').first()  # noqa

        hpbku = Candidate.objects.filter(position__name=PositionName.HPB.value, house=House.KUMI.value).order_by('ballot_number')  # noqa
        hpgku = Candidate.objects.filter(position__name=PositionName.HPG.value, house=House.KUMI.value).order_by('ballot_number')  # noqa

        context = {
            'current_election': current_election,
            'positions': positions_set_1,
            'positions_set_2': positions_set_2,
            'sps': sps,
            'gps': gps,
            'cob': cob,
            'cog': cog,
            'sgpb': sgpb,
            'sgpg': sgpg,
            'dhpb': dhpb,
            'dhpg': dhpg,
            'ecpb': ecpb,
            'ecpg': ecpg,
            'lpb': plpb,
            'lpg': plpg,
            'csb': csb,
            'csg': csg,
            # 'ppb': ppb,
            # 'ppg': ppg,
            'hspb': hspb,
            'hspg': hspg,
            'hpba': hpba,
            'hpga': hpga,
            'hpbb': hpbb,
            'hpgb': hpgb,
            'hpbka': hpbka,
            'hpgka': hpgka,
            'hpbku': hpbku,
            'hpgku': hpgku,
        }
        return render(request, self.template, context)

core/backend/views/elections.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.utils.html import strip_tags
from django.views.generic import View

from backend.models import Election
from backend.forms import ElectionForm
from core.utils.decorators import AdminOnly


class ElectionsView(View):
    template = 'backend/lists/elections.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        elections = Election.objects.all()
        context = {'elections': elections}
        return render(request, self.template, context)


class CreateUpdateElectionView(View):
    template = 'backend/create_update_election.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        election_id = request.GET.get('election_id')
        election = Election.objects.filter(id=election_id).first()
        context = {'election': election}
        return render(request, self.template, context)

    @method_decorator(AdminOnly)
    def post(self, request, *args, **kwargs):
        election_id = request.POST.get('election_id')
        election = Election.objects.filter(id=election_id).first() if election_id else None  # noqa
        form = ElectionForm(request.POST, instance=election)
        if form.is_valid():
            form.save()
            if election is not None:
                messages.success(request, 'Election Updated Successfully')
            else:
                messages.success(request, 'New Election Created Successfully')
            return redirect('backend:elections')
        else:
            for field, error in form.errors.items():
                message = f"{field.title()}: {strip_tags(error)}"
                break
            messages.warning(request, message)
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


class DeleteElectionView(View):
    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        return redirect('backend:elections')

    @method_decorator(AdminOnly)
    def post(self, request, *args, **kwargs):
        election_id = request.POST.get('election_id')
        election = Election.objects.filter(id=election_id).first()
        election.delete()
        messages.success(request, 'Election Deleted Successfully')
        return redirect('backend:elections')

core/backend/views/index.py
from django.shortcuts import render
from django.views import View
from accounts.models import User

from backend.models import Candidate, Election, Position
from django.utils.decorators import method_decorator
from core.utils.constants import House, PositionName
from core.utils.decorators import AdminOnly


class NewDashboardView(View):
    '''New view for displaying the dashboard'''
    template = 'backend/dashboard.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        current_election = Election.objects.all().first()
        candidates = Candidate.objects.all().order_by('position__precedence', 'ballot_number')  # noqa
        total_votes_cast = User.objects.filter(is_student=True, already_voted=True).count()  # noqa
        context = {
            'candidates': candidates,
            'total_votes_cast': total_votes_cast,
            'current_election': current_election,
        }
        return render(request, self.template, context)

core/backend/views/verification.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views.generic import View
from accounts.models import User

from core.utils.decorators import AdminOnly


class VerificationView(View):
    template = 'backend/verification.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        context = {}
        index_number = request.GET.get('index_number')
        voter = User.objects.filter(index_number=index_number, is_student=True).first()  # noqa
        if voter:
            messages.success(request, 'VOTER VERIFIED!')
            context = {'voter': voter}
            return render(request, self.template, context)
        else:
            print(index_number)
            if index_number is not None:
                messages.warning(request, 'VOTER NOT VERIFIED!')
            return render(request, self.template, context)

core/backend/templates/backend/forms/form_candidate.html
<form action="" class="needs-validation my-4" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <input type="hidden" name="candidate_id" value="{{candidate.id}}">

    <div class="form-group mt-3">
        <label for="name">Name <span class="text text-danger">*</span></label>
        <input class="form-control" placeholder="E.g., Prince Kyeremanteng S." value="{{candidate.name}}" type="text"
            name="name" id="name" required>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>
    <div class="form-group mt-3">
        <label for="nickname">Nickname <span class="text text-danger">*</span></label>
        <input class="form-control" placeholder="E.g., Earthquake." value="{{candidate.nickname}}" type="text"
            name="nickname" id="nickname">
    </div>
    <div class="form-group mt-3">
        <label for="sex">Sex <span class="text text-danger">*</span></label>
        <select name="sex" id="sex" class="form-control">
            <option value="---">---Select Sex---</option>
            <option value="F" {% if candidate.sex == "F" %} selected {% endif %}>F</option>
            <option value="M" {% if candidate.sex == "M" %} selected {% endif %}>M</option>
        </select>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>
    <div class="form-group mt-3">
        <label for="house">House <span class="text text-danger">*</span></label>
        <select name="house" id="house" class="form-control">
            <option value="---">---Select House---</option>
            <option value="ASANTE" {% if candidate.house == "ASANTE" %} selected {% endif %}>ASANTE</option>
            <option value="BOTWE" {% if candidate.house == "BOTWE" %} selected {% endif %}>BOTWE</option>
            <option value="KALEDZI" {% if candidate.house == "KALEDZI" %} selected {% endif %}>KALEDZI</option>
            <option value="KUMI" {% if candidate.house == "KUMI" %} selected {% endif %}>KUMI</option>
        </select>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>
    <div class="form-group mt-3">
        <label for="position">Position <span class="text text-danger">*</span></label>
        <select name="position" id="position" class="form-control">
            <option value="---">---Select Position---</option>
            {% for position in positions %}
            <option value="{{position.id}}" {% if position.id == candidate.position.id %} selected {% endif %}>
                {{position.name}}</option>
            {% endfor %}
        </select>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>
    <div class="form-group mt-3">
        <label for="ballot_number">Ballot Number <span class="text text-danger">*</span></label>
        <input class="form-control" placeholder="E.g., 1" value="{{candidate.ballot_number}}" type="number"
            name="ballot_number" id="ballot_number" min="1" step="1" required>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>

    <div class="form-group mt-3">
        <label for="image">IMAGE<span class="text text-danger">*</span></label>
        <small class="text text-primary p-0 m-0">{% if candidate.picture %}Currently: <a
                href="{{candidate.picture.url}}" target="_blank">{{candidate.picture.url}}</a>{% endif %}</small>
        <input class="form-control" type="file" accept="image/*" name="picture" id="picture"
            {% if not candidate.picture %}required{% endif %}>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>


    <div class="form-group my-3">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

core/backend/templates/backend/forms/form_election.html
<form action="" class="needs-validation my-4" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <input type="hidden" name="election_id" value="{{election.id}}">

    <div class="form-group mt-3">
        <label for="name">Name <span class="text text-danger">*</span></label>
        <input class="form-control" placeholder="E.g. TASHTECH 2018/19 GEN. ELECTION" value="{{election.name}}"
            type="text" name="name" id="name" required>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>
    <div class="form-group mt-3">
        <label for="description">Description <span class="text text-danger">*</span></label>
        <textarea name="description" id="description" class="form-control" cols="30"
            rows="6">{{election.description}}</textarea>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>
    <div class="form-group mt-3">
        <label for="name">Date of Election <span class="text text-danger">*</span></label> <br>
        {% if election.date_of_election %}
        <small>Current Date: <span class="text-primary">{{election.date_of_election}}</span></small>
        {% endif %}
        <input class="form-control" value="{{election.date_of_election}}" type="datetime-local" name="date_of_election"
            id="date_of_election" {% if not election.date_of_election %} required {% endif %}>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>


    <div class="form-group my-3">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

core/backend/templates/backend/forms/form_position.html
<form action="" class="needs-validation my-4" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <input type="hidden" name="position_id" value="{{position.id}}">

    <div class="form-group mt-3">
        <label for="name">Name <span class="text text-danger">*</span></label>
        <input class="form-control" placeholder="E.g., SRC PRESIDENT." value="{{position.name}}" type="text" name="name"
            id="name" required>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>
    <div class="form-group mt-3">
        <label for="precedence">Results Precedence <span class="text text-danger">*</span></label>
        <input class="form-control" placeholder="E.g., 1" value="{{position.precedence}}" type="number" min="1"
            name="precedence" id="precedence" required>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>


    <div class="form-group my-3">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

core/backend/templates/backend/forms/form_positions_file.html
<form action="{% url 'backend:upload_position_csv' %}" class="needs-validation my-4" enctype="multipart/form-data"
    method="POST">
    {% csrf_token %}

    <div class="form-group mt-3">
        <label for="csv_file">Positions File <span class="text text-danger">*</span></label>
        <input class="form-control" type="file" name="csv_file" id="csv_file" accept=".csv" required>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>

    <div class="form-group my-3">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

core/backend/templates/backend/forms/form_voter.html
<form action="" class="needs-validation my-4" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <input type="hidden" name="voter_id" value="{{voter.id}}">

    <div class="form-group mt-3">
        <label for="fullname">Fullname <span class="text text-danger">*</span></label>
        <input class="form-control" placeholder="E.g. Prince Kyeremanteng" value="{{voter.fullname}}" type="text"
            name="fullname" id="fullname" required>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>

    <div class="form-group mt-3">
        <label for="index_number">Index Number <span class="text text-danger">*</span></label>
        <input class="form-control" placeholder="E.g. 10841385" value="{{voter.index_number}}" type="text"
            name="index_number" id="index_number" required>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>

    <div class="form-group mt-3">
        <label for="user_class">Form / Class <span class="text text-danger">*</span></label>
        <input class="form-control" placeholder="E.g. FORM 2 A1" value="{{voter.user_class}}" type="text"
            name="user_class" id="user_class" required>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>
    <div class="form-group mt-3">
        <label for="status">Residence Status <span class="text text-danger">*</span></label>
        <select name="status" id="status" class="form-control">
            <option value="---">---Select Residence Status---</option>
            <option value="DAY" {% if voter.house == "DAY" %} selected {% endif %}>DAY</option>
            <option value="BOARDING" {% if voter.house == "BOARDING" %} selected {% endif %}>BOARDING</option>
        </select>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>
    <div class="form-group mt-3">
        <label for="house">House <span class="text text-danger">*</span></label>
        <select name="house" id="house" class="form-control">
            <option value="---">---Select House---</option>
            <option value="ASANTE" {% if voter.house == "ASANTE" %} selected {% endif %}>ASANTE</option>
            <option value="BOTWE" {% if voter.house == "BOTWE" %} selected {% endif %}>BOTWE</option>
            <option value="KALEDZI" {% if voter.house == "KALEDZI" %} selected {% endif %}>KALEDZI</option>
            <option value="KUMI" {% if voter.house == "KUMI" %} selected {% endif %}>KUMI</option>
        </select>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>
    <div class="form-group mt-3">
        <label for="sex">Sex <span class="text text-danger">*</span></label>
        <select name="sex" id="sex" class="form-control">
            <option value="---">---Select Sex---</option>
            <option value="F" {% if voter.sex == "F" %} selected {% endif %}>F</option>
            <option value="M" {% if voter.sex == "M" %} selected {% endif %}>M</option>
        </select>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>

    <div class="form-group my-3">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

core/backend/templates/backend/forms/form_voter_register.html
<form action="{% url 'backend:upload_register' %}" class="needs-validation my-4" enctype="multipart/form-data"
    method="POST">
    {% csrf_token %}

    <div class="form-group mt-3">
        <label for="csv_file">Voter Register <span class="text text-danger">*</span></label>
        <input class="form-control" type="file" name="csv_file" id="csv_file" accept=".csv" required>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>

    <div class="form-group my-3">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>