core/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    # path('', views.LandingPageView.as_view(), name='landing_page'),
    path('', views.LoginView.as_view(), name='login'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

core/backend/urls.py
from unicodedata import name
from django.urls import path
from . import views


app_name = 'backend'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.NewDashboardView.as_view(), name='index'),
]

# new dashboard
urlpatterns += [
    path('new-dashboard/', views.NewDashboardView.as_view(), name="new_dashboard"),
]

# Candidates
urlpatterns += [
    path('candidates/', views.CandidatesListView.as_view(), name='candidates'),
    path('create-update-candiddate/', views.CreateUpdateCandidateView.as_view(), name='create_update_candidate'),  # noqa
    path('delete-candidate/', views.DeleteCandidateView.as_view(), name='delete_candidate')  # noqa
]

# Positions
urlpatterns += [
    path('positions/', views.PositionsView.as_view(), name='positions'),
    path('create-update_position/', views.CreateUpdatePositionView.as_view(), name='create_update_position'),  # noqa
    path('upload-position-csv/', views.UploadPositionsFromCSV.as_view(), name='upload_position_csv'),  # noqa
    path('delete-position/', views.DeletePositionView.as_view(), name='delete_position'),  # noqa
]

# Elections
urlpatterns += [
    path('elections/', views.ElectionsView.as_view(), name='elections'),
    path('create-update_election/', views.CreateUpdateElectionView.as_view(), name='create_update_election'),  # noqa
    path('delete-election/', views.DeleteElectionView.as_view(), name='delete_election'),  # noqa
]

# Voters
urlpatterns += [
    path('voters/', views.VotersView.as_view(), name='voters'),
    path('create-update_voter/', views.CreateUpdateVoterView.as_view(), name='create_update_voter'),  # noqa
    path('delete-voter/', views.DeleteVoterView.as_view(), name='delete_voter'),  # noqa
    path('upload-register/', views.UploadVotersFromCSV.as_view(), name='upload_register'),  # noqa
]


# Verification
urlpatterns += [
    path('verification/', views.VerificationView.as_view(), name='verification'),
]

# Results
urlpatterns += [
    path('download-results-csv/', views.DownloadCandidateResultsAsCSVView.as_view(), name='download_results_csv'),  # noqa
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('backend/', include('backend.urls')),
    path('vote/', include('voting.urls')),
]

# Let django serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/backend/forms.py
from django import forms

from .models import Candidate, Election, Position


class CandidateForm(forms.ModelForm):
    '''Facilitates creation and updation of candidates'''
    class Meta:
        model = Candidate
        exclude = ['vote_count', 'position', 'created_at', 'no_votes_count']


class PositionForm(forms.ModelForm):
    '''Facilitates creation and updation of positions'''
    class Meta:
        model = Position
        exclude = ['created_at']


class ElectionForm(forms.ModelForm):
    '''Facilitates creation and updation of elections'''
    class Meta:
        model = Election
        exclude = ['created_at', 'is_active']

core/backend/views/candidates.py
import csv
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.utils.html import strip_tags
from django.views.generic import View
from django.http.response import HttpResponse
from backend.forms import CandidateForm

from backend.models import Candidate, Position
from core.utils.decorators import AdminOnly


class CandidatesListView(View):
    template = 'backend/lists/candidates.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        context = {'candidates': Candidate.objects.all().order_by('position__name', 'ballot_number')}  # noqa
        return render(request, self.template, context)


class CreateUpdateCandidateView(View):
    '''Class for creating and updating candidates'''
    template = 'backend/create_update_candidate.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        candidate_id = request.GET.get('candidate_id')
        candidate = Candidate.objects.filter(id=candidate_id).first()
        positions = Position.objects.all()
        context = {'positions': positions, 'candidate': candidate}
        return render(request, self.template, context)

    @method_decorator(AdminOnly)
    def post(self, request, *args, **kwargs):
        position_id = request.POST.get('position')
        candidate_id = request.POST.get('candidate_id')
        position = Position.objects.filter(id=position_id).first()

        if candidate_id:
            # candidate exists
            candidate = Candidate.objects.filter(id=candidate_id).first()
            form = CandidateForm(request.POST, request.FILES, instance=candidate)  # noqa
            if form.is_valid():
                candidate = form.save(commit=False)
                candidate.position = position
                candidate.save()
                messages.success(request, 'Candidate Details Updated Successfully.')  # noqa
                return redirect('backend:candidates')
            else:
                for field, error in form.errors.items():
                    message = f"{field.title()}: {strip_tags(error)}"
                    break
                messages.warning(request, message)
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
        else:
            # it's a new candidate
            form = CandidateForm(request.POST, request.FILES)
            if form.is_valid():
                candidate = form.save(commit=False)
                candidate.position = position
                candidate.save()
                messages.success(request, 'New Candidate Created Successfully.')  # noqa
                return redirect('backend:candidates')
            else:
                for field, error in form.errors.items():
                    message = f"{field.title()}: {strip_tags(error)}"
                    break
                messages.warning(request, message)
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


class DeleteCandidateView(View):
    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        return redirect('backend:candidates')

    @method_decorator(AdminOnly)
    def post(self, request, *args, **kwargs):
        candidate_id = request.POST.get('candidate_id')
        candidate = Candidate.objects.filter(id=candidate_id)
        candidate.delete()
        messages.success(request, 'Candidate Deleted Successfully!')
        return redirect('backend:candidates')


class DownloadCandidateResultsAsCSVView(View):
    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="election_results.csv"'  # noqa

        writer = csv.writer(response)
        writer.writerow(
            ['BALLOT NO.', 'POSITION', 'CANDIDATE', 'VOTES COUNT', 'NO VOTES', 'YES VOTE COUNT %', 'NO VOTES %'])  # noqa

        candidates = Candidate.objects.all().order_by('position__precedence', 'ballot_number')  # noqa
        for candidate in candidates:
            writer.writerow(
                [
                    candidate.ballot_number,
                    candidate.position.name,
                    candidate.name,
                    candidate.vote_count,
                    candidate.no_votes_count,
                    candidate.get_vote_percentage(),
                    candidate.get_no_vote_percentage(),
                ]
            )
        return response

core/backend/views/dashboard.py
from django.shortcuts import render
from django.views import View

from backend.models import Candidate, Election, Position
from django.utils.decorators import method_decorator
from core.utils.constants import House, PositionName
from core.utils.decorators import AdminOnly


class IndexView(View):
    template = 'backend/index.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        current_election = Election.objects.filter(is_active=True).order_by('created_at').first()  # noqa
        positions_set_1 = Position.objects.all().order_by('-id')[:10]
        positions_set_2 = Position.objects.all().order_by('-id')[10:]

        sps = Candidate.objects.filter(position__name=PositionName.SP.value).order_by('ballot_number')  # noqa
        gps = Candidate.objects.filter(position__name=PositionName.GP.value).order_by('ballot_number')  # noqa

        cob = Candidate.objects.filter(position__name=PositionName.COB.value).order_by('ballot_number')  # noqa
        cog = Candidate.objects.filter(position__name=PositionName.COG.value).order_by('ballot_number')  # noqa

        sgpb = Candidate.objects.filter(position__name=PositionName.SGPB.value).order_by('ballot_number')  # noqa
        sgpg = Candidate.objects.filter(position__name=PositionName.SGPG.value).order_by('ballot_number')  # noqa

        dhpb = Candidate.objects.filter(position__name=PositionName.DHPB.value).order_by('ballot_number')  # noqa
        dhpg = Candidate.objects.filter(position__name=PositionName.DHPG.value).order_by('ballot_number')  # noqa

        ecpb = Candidate.objects.filter(position__name=PositionName.ECPB.value).order_by('ballot_number')  # noqa
        ecpg = Candidate.objects.filter(position__name=PositionName.ECPG.value).order_by('ballot_number')  # noqa

        plpb = Candidate.objects.filter(position__name=PositionName.PLPB.value).order_by('ballot_number').first()  # noqa
        plpg = Candidate.objects.filter(position__name=PositionName.PLPG.value).order_by('ballot_number').first()  # noqa

        csb = Candidate.objects.filter(position__name=PositionName.CSB.value).order_by('ballot_number').first()  # noqa
        csg = Candidate.objects.filter(position__name=PositionName.CSG.value).order_by('ballot_number').first()  # noqa

        # ppb = Candidate.objects.filter(position__name=PositionName.PPB.value).order_by('ballot_number')  # noqa
        # ppg = Candidate.objects.filter(position__name=PositionName.PPG.value).order_by('ballot_number')  # noqa

        hspb = Candidate.objects.filter(position__name=PositionName.HSPB.value).order_by('ballot_number')  # noqa
        hspg = Candidate.objects.filter(position__name=PositionName.HSPG.value).order_by('ballot_number').first()  # noqa

        hpba = Candidate.objects.filter(position__name=PositionName.HPB.value, house=House.ASANTE.value).order_by('ballot_number').first()  # noqa
        hpga = Candidate.objects.filter(position__name=PositionName.HPG.value, house=House.ASANTE.value).order_by('ballot_number').first()  # noqa

        hpbb = Candidate.objects.filter(position__name=PositionName.HPB.value, house=House.BOTWE.value).order_by('ballot_number').first()  # noqa
        hpgb = Candidate.objects.filter(position__name=PositionName.HPG.value, house=House.BOTWE.value).order_by('ballot_number').first()  # noqa

        hpbka = Candidate.objects.filter(position__name=PositionName.HPB.value, house=House.KALEDZI.value).order_by('ballot_number').first()  # noqa
        hpgka = Candidate.objects.filter(position__name=PositionName.HPG.value, house=House.KALEDZI.value).order_by('ballot_number').first()  # noqa

        hpbku = Candidate.objects.filter(position__name=PositionName.HPB.value, house=House.KUMI.value).order_by('ballot_number')  # noqa
        hpgku = Candidate.objects.filter(position__name=PositionName.HPG.value, house=House.KUMI.value).order_by('ballot_number')  # noqa

        context = {
            'current_election': current_election,
            'positions': positions_set_1,
            'positions_set_2': positions_set_2,
            'sps': sps,
            'gps': gps,
            'cob': cob,
            'cog': cog,
            'sgpb': sgpb,
            'sgpg': sgpg,
            'dhpb': dhpb,
            'dhpg': dhpg,
            'ecpb': ecpb,
            'ecpg': ecpg,
            'lpb': plpb,
            'lpg': plpg,
            'csb': csb,
            'csg': csg,
            # 'ppb': ppb,
            # 'ppg': ppg,
            'hspb': hspb,
            'hspg': hspg,
            'hpba': hpba,
            'hpga': hpga,
            'hpbb': hpbb,
            'hpgb': hpgb,
            'hpbka': hpbka,
            'hpgka': hpgka,
            'hpbku': hpbku,
            'hpgku': hpgku,
        }
        return render(request, self.template, context)

core/backend/views/elections.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.utils.html import strip_tags
from django.views.generic import View

from backend.models import Election
from backend.forms import ElectionForm
from core.utils.decorators import AdminOnly


class ElectionsView(View):
    template = 'backend/lists/elections.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        elections = Election.objects.all()
        context = {'elections': elections}
        return render(request, self.template, context)


class CreateUpdateElectionView(View):
    template = 'backend/create_update_election.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        election_id = request.GET.get('election_id')
        election = Election.objects.filter(id=election_id).first()
        context = {'election': election}
        return render(request, self.template, context)

    @method_decorator(AdminOnly)
    def post(self, request, *args, **kwargs):
        election_id = request.POST.get('election_id')
        election = Election.objects.filter(id=election_id).first() if election_id else None  # noqa
        form = ElectionForm(request.POST, instance=election)
        if form.is_valid():
            form.save()
            if election is not None:
                messages.success(request, 'Election Updated Successfully')
            else:
                messages.success(request, 'New Election Created Successfully')
            return redirect('backend:elections')
        else:
            for field, error in form.errors.items():
                message = f"{field.title()}: {strip_tags(error)}"
                break
            messages.warning(request, message)
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


class DeleteElectionView(View):
    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        return redirect('backend:elections')

    @method_decorator(AdminOnly)
    def post(self, request, *args, **kwargs):
        election_id = request.POST.get('election_id')
        election = Election.objects.filter(id=election_id).first()
        election.delete()
        messages.success(request, 'Election Deleted Successfully')
        return redirect('backend:elections')

core/backend/views/index.py
from django.shortcuts import render
from django.views import View
from accounts.models import User

from backend.models import Candidate, Election, Position
from django.utils.decorators import method_decorator
from core.utils.constants import House, PositionName
from core.utils.decorators import AdminOnly


class NewDashboardView(View):
    '''New view for displaying the dashboard'''
    template = 'backend/dashboard.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        current_election = Election.objects.all().first()
        candidates = Candidate.objects.all().order_by('position__precedence', 'ballot_number')  # noqa
        total_votes_cast = User.objects.filter(is_student=True, already_voted=True).count()  # noqa
        context = {
            'candidates': candidates,
            'total_votes_cast': total_votes_cast,
            'current_election': current_election,
        }
        return render(request, self.template, context)

core/backend/views/verification.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views.generic import View
from accounts.models import User

from core.utils.decorators import AdminOnly


class VerificationView(View):
    template = 'backend/verification.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        context = {}
        index_number = request.GET.get('index_number')
        voter = User.objects.filter(index_number=index_number, is_student=True).first()  # noqa
        if voter:
            messages.success(request, 'VOTER VERIFIED!')
            context = {'voter': voter}
            return render(request, self.template, context)
        else:
            print(index_number)
            if index_number is not None:
                messages.warning(request, 'VOTER NOT VERIFIED!')
            return render(request, self.template, context)

core/backend/templates/backend/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    {% load humanize %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="TechStuff">
    <meta name="author" content="TechStuff">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/png">
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">

    <!-- extra css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>{% block page_title %}{% endblock %} | Tashtech Evoting Portal</title>

</head>

<body>
    <div id="main-overlay"></div>
    <!-- Sidebar -->
    <aside id="side-bar" data-active="{% block active_item %}dashboard{% endblock %}">
        <div class="header bg-white">
            <img src="{% static 'images/logo.png' %}" style="height: 50px; width:auto;" alt="">
        </div>

        <h6 class="item-header mt-3">Elections</h6>
        <div class="side-bar-item" title="Dashboard" id="dashboard">
            <a href="{% url 'backend:index' %}" class="d-flex">
                <div class="icon">
                    <i class="bi bi-bar-chart" style="font-size: 1.5em;"></i>
                </div>
                <div class="lable">
                    <span>Dashboard</span>
                </div>
            </a>
        </div>

        <div class="side-bar-item" title="elections" id="elections">
            <a href="{% url 'backend:elections' %}" class="d-flex">
                <div class="icon">
                    <i class="bi bi-bag" style="font-size: 1.5em;"></i>
                </div>
                <div class="lable">
                    <span>Elections</span>
                </div>
            </a>
        </div>
        <div class="side-bar-item" title="verification" id="verification">
            <a href="{% url 'backend:verification' %}" class="d-flex">
                <div class="icon">
                    <i class="bi bi-check-square" style="font-size: 1.5em;"></i>
                </div>
                <div class="lable">
                    <span>Verification</span>
                </div>
            </a>
        </div>


        <h6 class="item-header mt-3">OBJECTS</h6>
        <div class="side-bar-item" title="Category" id="categories">
            <a href="{% url 'backend:candidates' %}" class="d-flex">
                <div class="icon">
                    <i class="bi bi-collection" style="font-size: 1.5em;"></i>
                </div>
                <div class="lable">
                    <span>Candidates</span>
                </div>
            </a>
        </div>

        <div class="side-bar-item" title="Banners" id="banners">
            <a href="{% url 'backend:voters' %}" class="d-flex">
                <div class="icon">
                    <i class="bx bx-chalkboard" style="font-size: 1.5em;"></i>
                </div>
                <div class="lable">
                    <span>Voters</span>
                </div>
            </a>
        </div>

        <div class="side-bar-item" title="Locations" id="locations">
            <a href="{% url 'backend:positions' %}" class="d-flex">
                <div class="icon">
                    <i class="bi bi-people" style="font-size: 1.5em;"></i>
                </div>
                <div class="lable">
                    <span>Positions</span>
                </div>
            </a>
        </div>

        <!-- <div class="side-bar-item" title="Setup" id="setup">
            <a href="" class="d-flex">
                <div class="icon">
                    <i class="bi bi-sliders" style="font-size: 1.5em;"></i>
                </div>
                <div class="lable">
                    <span>Setup <span class="badge" style="background-color: gold;">Soon</span> </span>
                </div>
            </a>
        </div> -->

        <div class="side-bar-item" title="Logout" id="logout">
            <a href="{% url 'accounts:logout' %}" class="d-flex">
                <div class="icon">
                    <i class="bi bi-lock" style="font-size: 1.5em;"></i>
                </div>
                <div class="lable">
                    <span>Logout</span>
                </div>
            </a>
        </div>
    </aside>
    <!-- End Sidebar -->

    <main id="main-page">
        <nav id="main-nav">
            <div class="nav-left">
                <div class="nav-item">
                    <button id="toggle-side-bar" class="btn-white"><i class="bi bi-list"
                            style="font-size: 2rem;"></i></button>
                </div>
            </div>
            <div class="nav-right">
                <div class="nav-item">
                    <div class="dropdown">
                        <div class="rounded-profile-picture">
                            <img src="{% static 'images/favicon.png' %}" alt="User profile picture">
                        </div>
                        <h6 class="text m-1">{{request.user.username|upper}}</h6>
                        <button class="btn-white dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown" data-target=".content" aria-haspopup="true"
                            aria-expanded="false"></button>
                        <div class="content overlay-toggle">
                            <div class="my-3">
                                <p class="p-0 m-0 text text-center">{{request.user.username|upper}}</p>
                                <p class="p-0 m-0 text text-center text-muted">TechStuff</p>
                            </div>
                            <a class="drop-item"><i class="bi bi-person"></i> Profile</a>
                            <a href="{% url 'accounts:logout' %}" class="drop-item"><i class="bi bi-lock"></i>
                                Logout</a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>

        <div class="main-content">
            {% if messages %}
            {% for message in messages %}

            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                <p class="p-0 m-0 text text-center col-md-6 mx-auto">{{message}}</p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock %}
        </div>

        <section class="footer">
            © Copyright <a href="" class="text text-primary">KPS Technologies</a>. All Rights Reserved
        </section>
    </main>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.12.1/standard/ckeditor.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js"
        integrity="sha512-sW/w8s4RWTdFFSduOTGtk4isV1+190E/GghVffMA9XczdJ2MDzSzLEubKAs5h0wzgSJOQTRYyaz73L3d6RtJSg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'js/index.js' %}"></script>
</body>

</html>

core/backend/templates/backend/create_update_candidate.html
{% extends 'backend/base.html' %}
{% block active_item %}candidates{% endblock %}
{% block page_title %}Candidates{% endblock %}


{% block content %}
<div class="breadcrumb">
    <a href="{% url 'backend:index' %}">Dashboard</a>
    <a class="active"><i class="bi bi-chevron-right"></i> Candidates</a>
</div>
<div class="row col-md-11 mx-auto">
    <section class="card col-md-9 mx-auto p-3">
        <div class="d-flex justify-content-between">
            <h6>CREATE/UPDATE CANDIDATE</h6>
        </div>
        {% include 'backend/forms/form_candidate.html' %}
    </section>
</div>
{% endblock %}

core/backend/templates/backend/create_update_election.html
{% extends 'backend/base.html' %}
{% block active_item %}elections{% endblock %}
{% block page_title %}Elections{% endblock %}


{% block content %}
<div class="breadcrumb">
    <a href="{% url 'backend:index' %}">Dashboard</a>
    <a class="active"><i class="bi bi-chevron-right"></i> Elections</a>
</div>
<div class="row col-md-11 mx-auto">
    <section class="card col-md-9 mx-auto p-3">
        <div class="d-flex justify-content-between">
            <h6>CREATE/UPDATE ELECTION</h6>
        </div>
        {% include 'backend/forms/form_election.html' %}
    </section>
</div>
{% endblock %}

core/backend/templates/backend/dashboard.html
{% extends 'backend/base.html' %}
{% load humanize %}

{% block active_item %}dashboard{% endblock %}
{% block page_title %}Dashboard{% endblock %}

{% block content %}
<div class="breadcrumb">
    <a href="{% url 'backend:index' %}">Dashboard</a>
    <a class="active"><i class="bi bi-chevron-right"></i>Dashboard</a>
</div>

<div class="p-3 row-col-12">
    <h4 class="page-header"><i class="bi bi-sliders me-2"></i> Dashboard</h4>
    <p>Breakdown of the current election.</p>

    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <a href="{% url 'backend:download_results_csv' %}" class="btn btn-sm btn-primary text-white"> <i
                        class="bi bi-save"></i> Download Results</a>
                <div class="card mb-2 mt-1">
                    <div class="card-body my-auto py-auto">
                        <div class="row">
                            <div class="col-6"><span class="p mt-1 text-left badge bg-primary"> Current Election </span>
                            </div>
                            <div class="col-6 text-end">
                                <span class="p mt-1 text-right badge bg-primary">{{current_election}}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Total Votes Received</h5>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{total_votes_cast}}</h5>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            {% if candidates %}
            {% for candidate in candidates %}
            <div class="col-lg-3 mb-3">
                <div class="card">
                    <div class="card-body">
                        <b>Position</b>
                        <P class="card-text">{{candidate.position.name}}</P> <br>
                        <b>Candidate</b>
                        <p class="card-text">{{candidate.name}}</p> <br>
                        <b>Votes Count (YES) </b>
                        <p class="card-text">{{candidate.vote_count}} ({{candidate.get_vote_percentage}}%)</p> <br>
                        <b>Votes Count (NO) </b>
                        <p class="card-text">{{candidate.no_votes_count}} ({{candidate.get_no_vote_percentage}}%) </p>
                        <br>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <center>
                            <b>NO CANDIDATE RESULTS FOUND</b>
                        </center>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </section>



</div>
{% endblock %}