core/backend/urls.py
from unicodedata import name
from django.urls import path
from . import views


app_name = 'backend'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.NewDashboardView.as_view(), name='index'),
]

# new dashboard
urlpatterns += [
    path('new-dashboard/', views.NewDashboardView.as_view(), name="new_dashboard"),
]

# Candidates
urlpatterns += [
    path('candidates/', views.CandidatesListView.as_view(), name='candidates'),
    path('create-update-candiddate/', views.CreateUpdateCandidateView.as_view(), name='create_update_candidate'),  # noqa
    path('delete-candidate/', views.DeleteCandidateView.as_view(), name='delete_candidate')  # noqa
]

# Positions
urlpatterns += [
    path('positions/', views.PositionsView.as_view(), name='positions'),
    path('create-update_position/', views.CreateUpdatePositionView.as_view(), name='create_update_position'),  # noqa
    path('upload-position-csv/', views.UploadPositionsFromCSV.as_view(), name='upload_position_csv'),  # noqa
    path('delete-position/', views.DeletePositionView.as_view(), name='delete_position'),  # noqa
]

# Elections
urlpatterns += [
    path('elections/', views.ElectionsView.as_view(), name='elections'),
    path('create-update_election/', views.CreateUpdateElectionView.as_view(), name='create_update_election'),  # noqa
    path('delete-election/', views.DeleteElectionView.as_view(), name='delete_election'),  # noqa
]

# Voters
urlpatterns += [
    path('voters/', views.VotersView.as_view(), name='voters'),
    path('create-update_voter/', views.CreateUpdateVoterView.as_view(), name='create_update_voter'),  # noqa
    path('delete-voter/', views.DeleteVoterView.as_view(), name='delete_voter'),  # noqa
    path('upload-register/', views.UploadVotersFromCSV.as_view(), name='upload_register'),  # noqa
]


# Verification
urlpatterns += [
    path('verification/', views.VerificationView.as_view(), name='verification'),
]

# Results
urlpatterns += [
    path('download-results-csv/', views.DownloadCandidateResultsAsCSVView.as_view(), name='download_results_csv'),  # noqa
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('backend/', include('backend.urls')),
    path('vote/', include('voting.urls')),
]

# Let django serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/backend/forms.py
from django import forms

from .models import Candidate, Election, Position


class CandidateForm(forms.ModelForm):
    '''Facilitates creation and updation of candidates'''
    class Meta:
        model = Candidate
        exclude = ['vote_count', 'position', 'created_at', 'no_votes_count']


class PositionForm(forms.ModelForm):
    '''Facilitates creation and updation of positions'''
    class Meta:
        model = Position
        exclude = ['created_at']


class ElectionForm(forms.ModelForm):
    '''Facilitates creation and updation of elections'''
    class Meta:
        model = Election
        exclude = ['created_at', 'is_active']

core/backend/views/candidates.py
import csv
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.utils.html import strip_tags
from django.views.generic import View
from django.http.response import HttpResponse
from backend.forms import CandidateForm

from backend.models import Candidate, Position
from core.utils.decorators import AdminOnly


class CandidatesListView(View):
    template = 'backend/lists/candidates.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        context = {'candidates': Candidate.objects.all().order_by('position__name', 'ballot_number')}  # noqa
        return render(request, self.template, context)


class CreateUpdateCandidateView(View):
    '''Class for creating and updating candidates'''
    template = 'backend/create_update_candidate.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        candidate_id = request.GET.get('candidate_id')
        candidate = Candidate.objects.filter(id=candidate_id).first()
        positions = Position.objects.all()
        context = {'positions': positions, 'candidate': candidate}
        return render(request, self.template, context)

    @method_decorator(AdminOnly)
    def post(self, request, *args, **kwargs):
        position_id = request.POST.get('position')
        candidate_id = request.POST.get('candidate_id')
        position = Position.objects.filter(id=position_id).first()

        if candidate_id:
            # candidate exists
            candidate = Candidate.objects.filter(id=candidate_id).first()
            form = CandidateForm(request.POST, request.FILES, instance=candidate)  # noqa
            if form.is_valid():
                candidate = form.save(commit=False)
                candidate.position = position
                candidate.save()
                messages.success(request, 'Candidate Details Updated Successfully.')  # noqa
                return redirect('backend:candidates')
            else:
                for field, error in form.errors.items():
                    message = f"{field.title()}: {strip_tags(error)}"
                    break
                messages.warning(request, message)
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
        else:
            # it's a new candidate
            form = CandidateForm(request.POST, request.FILES)
            if form.is_valid():
                candidate = form.save(commit=False)
                candidate.position = position
                candidate.save()
                messages.success(request, 'New Candidate Created Successfully.')  # noqa
                return redirect('backend:candidates')
            else:
                for field, error in form.errors.items():
                    message = f"{field.title()}: {strip_tags(error)}"
                    break
                messages.warning(request, message)
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


class DeleteCandidateView(View):
    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        return redirect('backend:candidates')

    @method_decorator(AdminOnly)
    def post(self, request, *args, **kwargs):
        candidate_id = request.POST.get('candidate_id')
        candidate = Candidate.objects.filter(id=candidate_id)
        candidate.delete()
        messages.success(request, 'Candidate Deleted Successfully!')
        return redirect('backend:candidates')


class DownloadCandidateResultsAsCSVView(View):
    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="election_results.csv"'  # noqa

        writer = csv.writer(response)
        writer.writerow(
            ['BALLOT NO.', 'POSITION', 'CANDIDATE', 'VOTES COUNT', 'NO VOTES', 'YES VOTE COUNT %', 'NO VOTES %'])  # noqa

        candidates = Candidate.objects.all().order_by('position__precedence', 'ballot_number')  # noqa
        for candidate in candidates:
            writer.writerow(
                [
                    candidate.ballot_number,
                    candidate.position.name,
                    candidate.name,
                    candidate.vote_count,
                    candidate.no_votes_count,
                    candidate.get_vote_percentage(),
                    candidate.get_no_vote_percentage(),
                ]
            )
        return response

core/backend/views/dashboard.py
from django.shortcuts import render
from django.views import View

from backend.models import Candidate, Election, Position
from django.utils.decorators import method_decorator
from core.utils.constants import House, PositionName
from core.utils.decorators import AdminOnly


class IndexView(View):
    template = 'backend/index.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        current_election = Election.objects.filter(is_active=True).order_by('created_at').first()  # noqa
        positions_set_1 = Position.objects.all().order_by('-id')[:10]
        positions_set_2 = Position.objects.all().order_by('-id')[10:]

        sps = Candidate.objects.filter(position__name=PositionName.SP.value).order_by('ballot_number')  # noqa
        gps = Candidate.objects.filter(position__name=PositionName.GP.value).order_by('ballot_number')  # noqa

        cob = Candidate.objects.filter(position__name=PositionName.COB.value).order_by('ballot_number')  # noqa
        cog = Candidate.objects.filter(position__name=PositionName.COG.value).order_by('ballot_number')  # noqa

        sgpb = Candidate.objects.filter(position__name=PositionName.SGPB.value).order_by('ballot_number')  # noqa
        sgpg = Candidate.objects.filter(position__name=PositionName.SGPG.value).order_by('ballot_number')  # noqa

        dhpb = Candidate.objects.filter(position__name=PositionName.DHPB.value).order_by('ballot_number')  # noqa
        dhpg = Candidate.objects.filter(position__name=PositionName.DHPG.value).order_by('ballot_number')  # noqa

        ecpb = Candidate.objects.filter(position__name=PositionName.ECPB.value).order_by('ballot_number')  # noqa
        ecpg = Candidate.objects.filter(position__name=PositionName.ECPG.value).order_by('ballot_number')  # noqa

        plpb = Candidate.objects.filter(position__name=PositionName.PLPB.value).order_by('ballot_number').first()  # noqa
        plpg = Candidate.objects.filter(position__name=PositionName.PLPG.value).order_by('ballot_number').first()  # noqa

        csb = Candidate.objects.filter(position__name=PositionName.CSB.value).order_by('ballot_number').first()  # noqa
        csg = Candidate.objects.filter(position__name=PositionName.CSG.value).order_by('ballot_number').first()  # noqa

        # ppb = Candidate.objects.filter(position__name=PositionName.PPB.value).order_by('ballot_number')  # noqa
        # ppg = Candidate.objects.filter(position__name=PositionName.PPG.value).order_by('ballot_number')  # noqa

        hspb = Candidate.objects.filter(position__name=PositionName.HSPB.value).order_by('ballot_number')  # noqa
        hspg = Candidate.objects.filter(position__name=PositionName.HSPG.value).order_by('ballot_number').first()  # noqa

        hpba = Candidate.objects.filter(position__name=PositionName.HPB.value, house=House.ASANTE.value).order_by('ballot_number').first()  # noqa
        hpga = Candidate.objects.filter(position__name=PositionName.HPG.value, house=House.ASANTE.value).order_by('ballot_number').first()  # noqa

        hpbb = Candidate.objects.filter(position__name=PositionName.HPB.value, house=House.BOTWE.value).order_by('ballot_number').first()  # noqa
        hpgb = Candidate.objects.filter(position__name=PositionName.HPG.value, house=House.BOTWE.value).order_by('ballot_number').first()  # noqa

        hpbka = Candidate.objects.filter(position__name=PositionName.HPB.value, house=House.KALEDZI.value).order_by('ballot_number').first()  # noqa
        hpgka = Candidate.objects.filter(position__name=PositionName.HPG.value, house=House.KALEDZI.value).order_by('ballot_number').first()  # noqa

        hpbku = Candidate.objects.filter(position__name=PositionName.HPB.value, house=House.KUMI.value).order_by('ballot_number')  # noqa
        hpgku = Candidate.objects.filter(position__name=PositionName.HPG.value, house=House.KUMI.value).order_by('ballot_number')  # noqa

        context = {
            'current_election': current_election,
            'positions': positions_set_1,
            'positions_set_2': positions_set_2,
            'sps': sps,
            'gps': gps,
            'cob': cob,
            'cog': cog,
            'sgpb': sgpb,
            'sgpg': sgpg,
            'dhpb': dhpb,
            'dhpg': dhpg,
            'ecpb': ecpb,
            'ecpg': ecpg,
            'lpb': plpb,
            'lpg': plpg,
            'csb': csb,
            'csg': csg,
            # 'ppb': ppb,
            # 'ppg': ppg,
            'hspb': hspb,
            'hspg': hspg,
            'hpba': hpba,
            'hpga': hpga,
            'hpbb': hpbb,
            'hpgb': hpgb,
            'hpbka': hpbka,
            'hpgka': hpgka,
            'hpbku': hpbku,
            'hpgku': hpgku,
        }
        return render(request, self.template, context)

core/backend/views/elections.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.utils.html import strip_tags
from django.views.generic import View

from backend.models import Election
from backend.forms import ElectionForm
from core.utils.decorators import AdminOnly


class ElectionsView(View):
    template = 'backend/lists/elections.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        elections = Election.objects.all()
        context = {'elections': elections}
        return render(request, self.template, context)


class CreateUpdateElectionView(View):
    template = 'backend/create_update_election.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        election_id = request.GET.get('election_id')
        election = Election.objects.filter(id=election_id).first()
        context = {'election': election}
        return render(request, self.template, context)

    @method_decorator(AdminOnly)
    def post(self, request, *args, **kwargs):
        election_id = request.POST.get('election_id')
        election = Election.objects.filter(id=election_id).first() if election_id else None  # noqa
        form = ElectionForm(request.POST, instance=election)
        if form.is_valid():
            form.save()
            if election is not None:
                messages.success(request, 'Election Updated Successfully')
            else:
                messages.success(request, 'New Election Created Successfully')
            return redirect('backend:elections')
        else:
            for field, error in form.errors.items():
                message = f"{field.title()}: {strip_tags(error)}"
                break
            messages.warning(request, message)
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


class DeleteElectionView(View):
    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        return redirect('backend:elections')

    @method_decorator(AdminOnly)
    def post(self, request, *args, **kwargs):
        election_id = request.POST.get('election_id')
        election = Election.objects.filter(id=election_id).first()
        election.delete()
        messages.success(request, 'Election Deleted Successfully')
        return redirect('backend:elections')

core/backend/views/index.py
from django.shortcuts import render
from django.views import View
from accounts.models import User

from backend.models import Candidate, Election, Position
from django.utils.decorators import method_decorator
from core.utils.constants import House, PositionName
from core.utils.decorators import AdminOnly


class NewDashboardView(View):
    '''New view for displaying the dashboard'''
    template = 'backend/dashboard.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        current_election = Election.objects.all().first()
        candidates = Candidate.objects.all().order_by('position__precedence', 'ballot_number')  # noqa
        total_votes_cast = User.objects.filter(is_student=True, already_voted=True).count()  # noqa
        context = {
            'candidates': candidates,
            'total_votes_cast': total_votes_cast,
            'current_election': current_election,
        }
        return render(request, self.template, context)

core/backend/views/verification.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views.generic import View
from accounts.models import User

from core.utils.decorators import AdminOnly


class VerificationView(View):
    template = 'backend/verification.html'

    @method_decorator(AdminOnly)
    def get(self, request, *args, **kwargs):
        context = {}
        index_number = request.GET.get('index_number')
        voter = User.objects.filter(index_number=index_number, is_student=True).first()  # noqa
        if voter:
            messages.success(request, 'VOTER VERIFIED!')
            context = {'voter': voter}
            return render(request, self.template, context)
        else:
            print(index_number)
            if index_number is not None:
                messages.warning(request, 'VOTER NOT VERIFIED!')
            return render(request, self.template, context)

core/backend/templates/backend/lists/candidates.html
{% extends 'backend/base.html' %}

{% block active_item %}candidates{% endblock %}
{% block page_title %}Candidtates{% endblock %}


{% block content %}
<div class="breadcrumb">
    <a href="{% url 'backend:index' %}">Dashboard</a>
    <a class="active"><i class="bi bi-chevron-right"></i> Candidate</a>
</div>


<div class="p-3">
    <h4 class="page-header"><i class="bi bi-sliders me-2"></i> Candidates</h4>
    <div class="row">
        <section class="col-md-12 mt-3">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h5 class="card-title"><span>All Candidates</span></h5>
                    <div class="actions">
                        <a href="{% url 'backend:create_update_candidate' %}"
                            class="btn btn-sm btn-primary text-white"><i class="bi bi-plus"></i> Add
                            Candidate</a>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-sm data-table col-12" id="Candidates" style="min-width: 60em;">
                        <caption>List of Candidates</caption>
                        <thead>
                            <tr>
                                <th>Ballot No.</th>
                                <th>Picture</th>
                                <th>Name</th>
                                <th>Nickname</th>
                                <th>Position</th>
                                <th>Vote Count</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if candidates %}
                            {% for candidate in candidates %}
                            <tr>
                                <td>{{candidate.ballot_number}}</td>
                                <td>
                                    {% if candidate.picture %}
                                    <img src="{{candidate.picture.url}}" alt="{{candidate.name}}" height="40">
                                    {% else %}
                                    <span class="text text-danger">No Picture Found</span>
                                    {% endif %}
                                </td>
                                <td>{{candidate.name|upper}}</td>
                                <td>{{candidate.nickname|upper}}</td>
                                <td>{{candidate.position.name|upper}}</td>
                                <td>{{candidate.vote_count}}</td>
                                <td class="text text-center d-flex">
                                    <a href="{% url 'backend:create_update_candidate' %}?candidate_id={{candidate.id}}"
                                        class="px-2">
                                        <button class="btn btn-sm btn-primary">
                                            <i class="bi bi-pencil"></i>
                                            Edit
                                        </button>
                                    </a>

                                    <form action="{% url 'backend:delete_candidate' %}" method="POST"
                                        class="requires-confirmation"
                                        data-message="Click on okay to permanently delete this candidate.">
                                        <input type="hidden" name="candidate_id" value="{{candidate.id}}">
                                        {% csrf_token %}
                                        <button class="btn btn-sm btn-danger">
                                            <i class="bi bi-trash"></i>
                                            Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>No Candidates Found</tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </section>

    </div>
</div>




{% endblock %}

core/backend/templates/backend/lists/elections.html
{% extends 'backend/base.html' %}

{% block active_item %}elections{% endblock %}
{% block page_title %}Elections{% endblock %}


{% block content %}
<div class="breadcrumb">
    <a href="{% url 'backend:index' %}">Dashboard</a>
    <a class="active"><i class="bi bi-chevron-right"></i> Elections</a>
</div>


<div class="p-3">
    <h4 class="page-header"><i class="bi bi-sliders me-2"></i> Elections</h4>
    <div class="row">
        <section class="col-md-12 mt-3">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h5 class="card-title"><span>All Elections</span></h5>
                    <div class="actions">
                        <a href="{% url 'backend:create_update_election' %}"
                            class="btn btn-sm btn-primary text-white"><i class="bi bi-plus"></i> Add
                            Election</a>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-sm data-table col-12" id="Elections" style="min-width: 60em;">
                        <caption>List of Elections</caption>
                        <thead>
                            <tr>
                                <th>Election No.</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Date of Election</th>
                                <td>Active</td>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if elections %}
                            {% for election in elections %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{election.name|upper}}</td>
                                <td>{{election.description}}</td>
                                <td>{{election.date_of_election}}</td>
                                <td>{{election.is_active}}</td>
                                <td class="text text-center d-flex">
                                    <a href="{% url 'backend:create_update_election' %}?election_id={{election.id}}"
                                        class="px-2">
                                        <button class="btn btn-sm btn-primary">
                                            <i class="bi bi-pencil"></i>
                                            Edit
                                        </button>
                                    </a>

                                    <form action="{% url 'backend:delete_election' %}" method="POST"
                                        class="requires-confirmation"
                                        data-message="Click on okay to permanently delete this election.">
                                        <input type="hidden" name="election_id" value="{{election.id}}">
                                        {% csrf_token %}
                                        <button class="btn btn-sm btn-danger">
                                            <i class="bi bi-trash"></i>
                                            Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>No Elections Found</tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </section>

    </div>
</div>




{% endblock %}

core/backend/templates/backend/lists/positions.html
{% extends 'backend/base.html' %}

{% block active_item %}positions{% endblock %}
{% block page_title %}Positions{% endblock %}


{% block content %}
<div class="breadcrumb">
    <a href="{% url 'backend:index' %}">Dashboard</a>
    <a class="active"><i class="bi bi-chevron-right"></i> Positions</a>
</div>


<div class="p-3">
    <h4 class="page-header"><i class="bi bi-sliders me-2"></i> Positions</h4>
    <div class="row">
        <section class="col-md-12 mt-3">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h5 class="card-title"><span>All Positions</span></h5>
                    <div class="actions">
                        <a href="{% url 'backend:create_update_position' %}"
                            class="btn btn-sm btn-primary text-white"><i class="bi bi-plus"></i> Add
                            Position</a>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-sm data-table col-12" id="Positions" style="min-width: 60em;">
                        <caption>List of Positions</caption>
                        <thead>
                            <tr>
                                <th>Position No.</th>
                                <th>Name</th>
                                <th>Candidates</th>
                                <th>Votes Cast</th>
                                <th>Precedence</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if positions %}
                            {% for position in positions %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{position.name|upper}}</td>
                                <td>{{position.get_candidates}}</td>
                                <td>{{position.get_votes_cast}}</td>
                                <td>{{position.precedence}}</td>
                                <td class="text text-center d-flex">
                                    <a href="{% url 'backend:create_update_position' %}?position_id={{position.id}}"
                                        class="px-2">
                                        <button class="btn btn-sm btn-primary">
                                            <i class="bi bi-pencil"></i>
                                            Edit
                                        </button>
                                    </a>

                                    <form action="{% url 'backend:delete_position' %}" method="POST"
                                        class="requires-confirmation"
                                        data-message="Click on okay to permanently delete this position.">
                                        <input type="hidden" name="position_id" value="{{position.id}}">
                                        {% csrf_token %}
                                        <button class="btn btn-sm btn-danger">
                                            <i class="bi bi-trash"></i>
                                            Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>No Positions Found</tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </section>

    </div>
</div>




{% endblock %}